import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import { useAccount } from 'wagmi';
import { Grid } from '../components/Grid';

const DEFAULT_ADDRESS = '0x0ED6Cec17F860fb54E21D154b49DAEFd9Ca04106';

export default function Home() {
  const { address } = useAccount();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ConnectButton />

        <h1 className='text-4xl font-bold'>
          Your on-chain mainnet activity in 2022
        </h1>

        <hr className='my-4' />

        <span className='text-xl font-bold'>
          Showing data for wallet address:
        </span>
        <span className='text-xl'>{address || DEFAULT_ADDRESS}</span>

        <Grid walletAddress={address || DEFAULT_ADDRESS} />
      </main>
    </>
  );
}
